apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - customer-service.yaml
  - product-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - logistics-service.yaml
  - sales-service.yaml
  - admin-portal.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: ecommerce-platform
